package com.cjl.travelblog

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import com.cjl.travelblog.databinding.ActivityLoginBinding

class login : AppCompatActivity() {

    //Using lateinit helps us avoid using the ? operator and reduces redundant code
    //But we must insure variable is initialized before using it
    private lateinit var binding: ActivityLoginBinding

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        //The ActivityLoginBinding class is autogenerated when the activity_login xml is created
        //the Android library just removes the underscores and capitalizes it
        //The layout inflater creates a view, which is then binded and set as this activities view
        binding = ActivityLoginBinding.inflate(layoutInflater)

        setContentView(binding.getRoot())
        //Lambda expression way of using an anonymous function
        binding.btnLogin.setOnClickListener({onLoginClicked()})

    }

    private fun onLoginClicked() {
        val userName = binding.textUsernameLayout.editText?.text.toString()
        val password = binding.edPassword.editText?.text.toString()

        if(userName.equals("")){
            binding.textUsernameLayout.error = "Username must not be empty"
        }else if(password.equals("")){
            binding.edPassword.error = "Password must not be empty"
        }

    }
}